<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-container">
    <div class="header-content">
        <div class="nav-container">
            <?php if ($this->getIsHomePage()):?>
            <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>

            <div class="header">
                <div class="quick-access">
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('topSearch') ?>
                    <div class="quick-access-link">
                        <?php echo $this->getChildHtml('topLinks') ?>
                    </div>
                    <?php echo $this->getChildHtml('cart_sidebar')?>
                </div>
                <?php echo $this->getChildHtml('topContainer'); ?>
            </div>

            <div class="menu-box">
                <?php echo $this->getChildHtml('cms_mainmenu', true) ?>
                <script type="text/javascript">
                    jQuery(document).ready(function(){
                        jQuery('div.header-container div.menu-box ul.menu > li').hover(
                            function(e) {
                                jQuery(this).find('.spacer').show();

                                var $color = jQuery(this).find('a:first').attr('data-color');
                                jQuery(this).css('background', $color);
                            },
                            function() {
                                jQuery(this).find('.spacer').hide();
                                jQuery(this).css('background', 'none');
                            }
                        );

                        jQuery('div.header-container div.menu-box ul.menu > li').each(function() {
                            var $cur   = jQuery(this),
                                $link  = $cur.find('a:first'),
                                $color = $link.attr('data-color'),
                                $els   = [];

                            if ($cur.position().top == 15) {
                                var $spacer = jQuery('<div>',{
                                    class: "spacer",
                                    style: "display:none"
                                });
                                $cur.find('div:first').before($spacer);

                                $els.push($spacer);
                            }

                            $els.push($cur.find('div:not(.spacer):first'));
                            $els.each(function(el)  {
                                jQuery(el).css('background', $color);
                            });

                            $link.hover(function() {
                                jQuery(this).parents('li').css('background', $color);
                            });
                        })
                    })
                </script>
            </div>
        </div>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
<?php echo $this->getChildHtml('delivery_promoter') ?>
