<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
    <?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <?php $pageTitle= $this->getLayout()->getBlock('head')->getTitle(); ?>
        <?php if ($this->getUrl('') == $this->getUrl(' * / * / * ', array('_current'=>true, '_use_rewrite'=>true))){?>
			<?php echo $this->getChildHtml('slideshow') ?>
			<?php echo $this->getChildHtml('brands_slider') ?>
			<?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('home-cat')->toHtml() ?>
        <?php } ?>
        <div class="main-container col1-layout">
            <div class="main">
                <?php echo $this->getChildHtml('breadcrumbs') ?>
                <div class="col-main">
                    <div class="col-inner" id="col-inner">
                        <?php echo $this->getChildHtml('global_messages') ?>
                        <?php echo $this->getChildHtml('products_slider') ?>			
                        <?php echo $this->getChildHtml('content') ?>
                        <?php echo $this->getChildHtml('dailytopproduct') ?>
                        <?php echo $this->getChildHtml('exdressme') ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>