<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_cartQty = Mage::getSingleton('checkout/cart')->getSummaryQty()?Mage::getSingleton('checkout/cart')->getSummaryQty():'0'; ?>
<?php $_links = $this->getLinks(); ?>
<?php if(count($_links)>0): ?>
<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
    <?php foreach($_links as $_link): ?>
        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
            <?php echo $_link->toHtml() ?>
        <?php else: ?>
            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
        <?php endif;?>
    <?php endforeach; ?>
    <?php
        $_subtotals = Mage::getSingleton('checkout/cart')->getQuote()->getTotals();
        $subtotal = $_subtotals["subtotal"]->getValue();
    ?>
    <?php $stringcart ='&nbsp;' . Mage::helper('checkout')->formatPrice($subtotal); ?>
    <li class="top-cart varnish-reload" id="top_cart_header" rel="top_cart_header"><?php echo $this->__('<a href="%s" class="top-link-cart" id="topcartlink">Shopping Cart %s Item(s) %s </a>', $this->getUrl('checkout/cart'), $_cartQty, $stringcart) ?></li>
</ul>
<?php endif; ?>
<script type="text/javascript">
	Varnish.addTemplate('top_cart_header',
			'<?php echo $this->__('<a %s class="top-link-cart" id="topcartlink">Shopping Cart %s Item(s) %s </a>', '{{href}}', '{{qty}}', '{{subtotal}}') ?>'
	);

	Varnish.addCallBack('top_cart_header', function(){
		Varnish.setTopCart({
					reload_id: 'block-cart'
				}
		);

		jQuery('#topcartlink').click(function(e){
			e.preventDefault();
			Varnish.getTopCart();
		});
	});

	Varnish.addTemplate('login_link',
			'<a href="{{url}}">{{text}}</a>'
	);
</script>

