<?php
/**
 * Magento
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2010 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 *
 * Shopping cart template
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="cart">
    <div class="cart-container">
        <div class="cart-container-inner">
            <div class="page-title title-buttons">
                <h1><?php echo $this->__('Shopping Cart') ?></h1>
                <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                <?php foreach ($this->getMethods('top_methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>

            <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

            <?php echo $this->getChildHtml('form_before') ?>

            <form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table">
                    <col width="1" />
                    <col />
                    <col width="1" />
                    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                    <?php endif ?>
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                    <?php endif; ?>
                    <col width="1" />
                    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                    <?php endif; ?>
                    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                    <?php endif; ?>
                    <col width="1" />

                    <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                        <tr>
                            <th  class="first" rowspan="<?php echo $mergedCells; ?>" colspan="2"><?php echo $this->__('Product Name') ?></th>
                            <!--th rowspan="<?php echo $mergedCells; ?>"><span class="nobr">&nbsp;</span></th-->
                            <!--th rowspan="<?php echo $mergedCells; ?>"></th-->
                            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><span class="nobr"><?php echo $this->__('Move to Wishlist') ?></span></th>
                            <?php endif ?>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><span class="nobr"><?php echo $this->__('price') ?></span></th>
                            <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('quantity') ?></th>
                            <th class="a-center" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('subtotal') ?></th>
                            <th class="last" rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('remove')?></th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                        <?php endif; ?>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="50" class="a-right">
                                <?php if($this->getContinueShoppingUrl()): ?>
                                    <button type="button" title="<?php echo $this->__('Continue Shopping') ?>"
                                            class="button btn-continue"
                                            onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')"
                                    >
                                        <span><span><?php echo $this->__('Continue Shopping') ?></span></span>
                                    </button>
                                <?php endif; ?>
                                <button type="submit"
                                        title="<?php echo $this->__('Update Shopping Cart') ?>"
                                        class="button btn-update"
                                >
                                    <span><span><?php echo $this->__('Update Shopping Cart') ?></span></span>
                                </button>
                            </td>
                        </tr>
                    </tfoot>
                    <tbody>
                        <?php foreach($this->getItems() as $_item): ?>
                            <?php echo $this->getItemHtml($_item) ?>
                        <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">
                        jQuery("div.quantity").append('<input type="button" value="+" id="add1" class="plus" />').prepend('<input type="button" value="-" id="minus1" class="minus" />');
                        jQuery(".plus").click(function(){
                            var currentVal = parseInt(jQuery(this).prev(".qty").val());
                            if (!currentVal || currentVal=="" || currentVal == "NaN") currentVal = 0;
                            jQuery(this).prev(".qty").val(currentVal + 1);
                        });
                        jQuery(".minus").click(function(){
                            var currentVal = parseInt(jQuery(this).next(".qty").val());
                            if (currentVal == "NaN") currentVal = 0;
                            if (currentVal > 0){
                                jQuery(this).next(".qty").val(currentVal - 1);
                            }
                        });
                </script>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </fieldset>
            </form>
        </div>
    </div>
    <div class="cart-collaterals">
        <div class="col2-set">
            <div class="col-2">
                <?php echo $this->getChildHtml('coupon') ?>
                <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
            </div>
        </div>
        <div class="totals">
            <div class="totals-inner">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
            </div>
        </div>
        <div class="col-1">
            <?php echo $this->getChildHtml('crosssell') ?>
        </div>
    </div>
</div>
