<?php 
if(isset($_COOKIE['XDEBUG_SESSION']) && $_COOKIE['XDEBUG_SESSION'] = 'PHPSTORM'){
	$xhprof_data = xhprof_disable();

	$XHPROF_ROOT = "/usr/share/php";
	include_once $XHPROF_ROOT . "/xhprof_lib/utils/xhprof_lib.php";
	include_once $XHPROF_ROOT . "/xhprof_lib/utils/xhprof_runs.php";

	$xhprof_runs = new XHProfRuns_Default();
	$run_id = $xhprof_runs->save_run($xhprof_data, "xhprof_testing");

	echo '<a href="http://' . $_SERVER['HTTP_HOST'] . "/xhprof_html/index.php?run={$run_id}&source=xhprof_testing" . '">report</a>';
}
